### ISSUE TITLE
Finish the exercise!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/f-m2-evaluacion-intermedia-MartaSobrino#1]
Really cool job @MartaSobrino  !!!

Here you have some tips to improve the exercise:

- [x] Define the logic to generate and save the random number (remember we gave you a sample code)
- [x] If you call 'getRandomNumer' function inside the event callback, you will be creating a new random number each time the user clicks the button. That makes the game really complex and the hints will not have sense. Let's generate the random number when the page loads instead.
- [x] Define the logic to make the counter work
- [x] Move you counter logic into a function and execute it on each click
- [x] You are writing many times "trackEl.innerHTML = 'something';", what about making a function that accepts a string as param and paints it into 'trackEl'?
- [x] Define a good structure of folders and files for the project
- [x] Add HTML elements for the game: title, label and input, button, space for feedback (`div`, `p`) and number of trials

You are close to the exercise solution, but here you have a steps guide to complete it anyway ;)

1. Save a reference to DOM elements in variables
2. Generate the random number and save it to a variable
3. Init counter of trials to 0
4. Define a function that executes when the user clicks on the button, that
  - increments the counter and paints its value in the HTML
  - collect the value of the HTML input and compare it with the random number
    - if they are equal, draw a 'You Win' message
    - if it's lower, draw a 'Too short' message
    - if it's higher, draw a 'Too long' message
5. Assign a listener to the button click to execute the previous function

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

Let me know if you have any doubts ;)

Go for it!!

**Comment by MartaSobrino** [comment]
I don't understand properly this issue:  You are writing many times "trackEl.innerHTML = 'something';", what about making a function that accepts a string as param and paints it into 'trackEl'?
Could you explain me in other way?
Thanks

**Comment by oneeyedman** [comment]
Sure I can! That was an example, in your exercise you are writing many times `result.innerHTML=`, so what about making a function that accepts a string as a param and paints it into the `result` element? :)

**Comment by oneeyedman** [comment]
Superb, @MartaSobrino ! 

If your up to a challenge check out these exercises from previous Adalabers:

- http://beta.adalab.es/dorcas-s2-evaluacion-intermedia-mariavioleta1417/
- http://beta.adalab.es/e-s2-evaluacion-intermedia-maria-badanina/
- http://beta.adalab.es/dorcar-s2-evaluacion-intermedia-annabranco/
- http://beta.adalab.es/e-s2-evaluacion-intermedia-beatrizAdalab/

;) 

Here you have a cool gif:
![well done](https://media.giphy.com/media/26uffIRfNMzrTCvok/giphy.gif)
